### ISSUE TITLE
Chapter 2: Deprecated method

### ISSUE THREAD

**Issue by codeweb** [PacktPublishing/TypeScript-Blueprints#2]
In chapter 2 of downloaded code, index.js 19770:5  i have the following warning:
Template parse warnings:
"#" inside of expressions is deprecated. Use "let" instead! ("

I think you can edit it.

**Comment by sonam-packt** [comment]
Please reopen the issue if still persist.

**Comment by codeweb** [comment]
You closed all my tickets without checking for them. So why do you use github?
